from enum import StrEnum


class AuditAction(StrEnum):
    """Enumeration of all auditable actions within the system."""

    ACCOUNT_REGISTERED = "ACCOUNT_REGISTERED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    MFA_SETUP_INITIATED = "MFA_SETUP_INITIATED"
    MFA_ENABLED = "MFA_ENABLED"
    MFA_DISABLED = "MFA_DISABLED"
    MFA_VERIFIED = "MFA_VERIFIED"
    MFA_FAILED = "MFA_FAILED"
    DEVICE_TRUSTED = "DEVICE_TRUSTED"
    DEVICE_REVOKED = "DEVICE_REVOKED"
    SSO_LOGIN_GOOGLE = "SSO_LOGIN_GOOGLE"
    SSO_ACCOUNT_LINKED = "SSO_ACCOUNT_LINKED"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
    ALL_SESSIONS_REVOKED = "ALL_SESSIONS_REVOKED"
